### ISSUE TITLE
Syncing mental model

### ISSUE THREAD

**Issue by microwavedcola1** [blockworks-foundation/distribute-by-locked-vote-weight#1]
So I am assuming CreateDistribution would be called by the dao? Can we have multiple distributions running parallely? Update: I see an index in pda derivation, I am assuming yes

The funds to be distributed e.g. fees earned by mango would be then transferred to the vault of the Distribution? So we would need proposals every month or whatever?

The participant will be newly created per distribution?  Update: I see a close particpant todo in claim ix

**Comment by ckamm** [comment]
Yes exactly:
- DAO would call CreateDistribution and transfer funds to the associated token account
- If a DAO wanted to distribute fees regularly they'd currently need to do this explicitly every month, yep. An automatic mechanism could be done, but I didn't think that should be in the first milestone.
- Each admin key can have multiple Distributions going on at the same time, via the index arg
- Yes, each participant needs a PDA (so we can know they've registered for participation when they later want to claim), and that should be closed when claiming imo

**Comment by microwavedcola1** [comment]
Agree with all points, cant the admin already be some governance account?

**Comment by microwavedcola1** [comment]
Also if I am not mistaken create participant ix is permission-less, right? I think that is how it should be, we could then create participants based on some script to improve UX so people dont have to manually go around creating them for every distribution everytime

**Comment by ckamm** [comment]
Yes, it should be permissionless, I made it so. Yes, admin could be a governance.
